name: Ansible Automation for the Python "venv"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: simalpi

    steps:
      - uses: actions/checkout@v3

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: project-number-one.yml

